services:
  postgres:
    build:
      dockerfile: ./docker/postgresql/Dockerfile
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
    ports:
      - "5432:5432"
  postgres-test:
    build:
      dockerfile: ./docker/postgresql/Dockerfile
    environment:
      - POSTGRES_DB=blog-test
      - POSTGRES_USER=blog-test
      - POSTGRES_PASSWORD=blog-test
    ports:
      - "5433:5432"   
